spring:
  cloud:
    aws:
      endpoint: http://localhost:4566
      credentials:
        access-key: test
        secret-key: test
      region:
        static: us-east-1
      sqs:
        endpoint: http://localhost:4566

cloud:
  aws:
    sqs:
      first-queue: first-SQS
      second-queue: second-SQS
      third-queue: third-SQS