version: '3'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:2.3.2
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=sqs
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./localstack-scripts:/etc/localstack/init/ready.d
      - ./localstack-scripts/sqs-messages:/tmp/localstack/sqs-messages
      - /var/run/docker.sock:/var/run/docker.sock
